# Generated by Django 3.1 on 2020-08-16 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20200816_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='open_countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
    ]
