# Generated by Django 3.1 on 2020-08-16 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20200816_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='open_with_retrictions_countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='open_countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open', to='countries.country'),
        ),
    ]
