# Generated by Django 3.1 on 2020-08-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20200816_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='closed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close', to='countries.country'),
        ),
        migrations.AddField(
            model_name='country',
            name='info',
            field=models.CharField(default='sadf', max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='open_with_retrictions_countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_with_restictions', to='countries.country'),
        ),
    ]
