# Generated by Django 3.1 on 2020-08-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_auto_20200816_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='info',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
