# Generated by Django 3.1 on 2020-08-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20200816_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='info',
        ),
        migrations.RemoveField(
            model_name='country',
            name='closed',
        ),
        migrations.AddField(
            model_name='country',
            name='closed',
            field=models.ManyToManyField(related_name='_country_closed_+', to='countries.Country'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='open_countries',
        ),
        migrations.AddField(
            model_name='country',
            name='open_countries',
            field=models.ManyToManyField(related_name='_country_open_countries_+', to='countries.Country'),
        ),
        migrations.RemoveField(
            model_name='country',
            name='open_with_retrictions_countries',
        ),
        migrations.AddField(
            model_name='country',
            name='open_with_retrictions_countries',
            field=models.ManyToManyField(related_name='_country_open_with_retrictions_countries_+', to='countries.Country'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'open'), ('2', 'open with restrictions'), ('3', 'closed'), ('4', 'unknown')], default='4', max_length=1)),
                ('info', models.CharField(default='', max_length=160)),
                ('arrival_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='countries.country')),
                ('departure_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='countries.country')),
            ],
        ),
    ]
