# Generated by Django 3.1 on 2020-08-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_auto_20200816_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='closed',
            field=models.ManyToManyField(null=True, related_name='_country_closed_+', to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='open_countries',
            field=models.ManyToManyField(null=True, related_name='_country_open_countries_+', to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='open_with_retrictions_countries',
            field=models.ManyToManyField(null=True, related_name='_country_open_with_retrictions_countries_+', to='countries.Country'),
        ),
    ]
